# Generated by Django 4.1.7 on 2023-04-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=200, null=True)),
                ('registration', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=14, null=True)),
                ('course', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
