# Generated by Django 4.1.7 on 2023-04-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=200, null=True)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=14, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
